services:
  - type: web
    name: cheema-dairy-frontend
    runtime: static
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        sync: false
    autoDeploy: true
